/**
 * تعريفات الإجراءات الإضافية (الحقول والتسميات) المقابلة لـ direct-actions-extra.server.ts.
 * تُدمج مع القائمة الأساسية لتغطية كل خصائص كل منصة — لا مجرد «إنشاء عنصر».
 */
import type { EmployeeActionDef } from "./employee-actions.server";

const req = (name: string, label: string) => ({ name, label, required: true });
const optn = (name: string, label: string) => ({ name, label });

export const extraEmployeeActions: EmployeeActionDef[] = [
  /* ————— أمَل: البريد والتقويم ————— */
  {
    id: "eva-gmail-reply",
    employeeId: "eva",
    provider: "gmail",
    label: "الرد داخل نفس خط البريد (جيميل)",
    inputs: [req("messageId", "معرّف الرسالة"), req("body", "نص الرد"), optn("to", "المستلم (اختياري)")],
  },
  {
    id: "eva-gmail-label",
    employeeId: "eva",
    provider: "gmail",
    label: "تصنيف/أرشفة رسالة",
    inputs: [
      req("messageId", "معرّف الرسالة"),
      optn("addLabelIds", "تصنيفات تُضاف (مفصولة بفاصلة)"),
      optn("removeLabelIds", "تصنيفات تُزال (مثل INBOX)"),
    ],
  },
  {
    id: "eva-gmail-search",
    employeeId: "eva",
    provider: "gmail",
    label: "بحث في البريد",
    inputs: [req("query", "استعلام البحث"), optn("max", "عدد النتائج")],
  },
  {
    id: "eva-outlook-reply",
    employeeId: "eva",
    provider: "outlook",
    label: "الرد على رسالة أوتلوك",
    inputs: [req("messageId", "معرّف الرسالة"), req("comment", "نص الرد")],
  },
  {
    id: "eva-outlook-draft",
    employeeId: "eva",
    provider: "outlook",
    label: "حفظ مسودة في أوتلوك",
    inputs: [req("to", "المستلمون"), req("subject", "الموضوع"), req("body", "النص")],
  },
  {
    id: "eva-calendar-update",
    employeeId: "eva",
    provider: "calendar",
    label: "تعديل موعد قائم",
    inputs: [
      req("eventId", "معرّف الموعد"),
      optn("summary", "العنوان"),
      optn("start", "البداية"),
      optn("end", "النهاية"),
    ],
  },
  {
    id: "eva-calendar-cancel",
    employeeId: "eva",
    provider: "calendar",
    label: "إلغاء موعد وإبلاغ الحضور",
    inputs: [req("eventId", "معرّف الموعد")],
  },
  {
    id: "eva-calendar-freebusy",
    employeeId: "eva",
    provider: "calendar",
    label: "أوقات الفراغ والانشغال",
    inputs: [req("timeMin", "من"), req("timeMax", "إلى"), optn("calendars", "تقاويم إضافية")],
  },
  {
    id: "eva-zoom-recordings",
    employeeId: "eva",
    provider: "zoom",
    label: "تسجيلات اجتماع زوم",
    inputs: [req("meetingId", "معرّف الاجتماع")],
  },
  {
    id: "eva-whatsapp-media",
    employeeId: "eva",
    provider: "whatsapp",
    label: "إرسال صورة/ملف على واتساب",
    inputs: [
      req("to", "رقم المستلم"),
      req("link", "رابط الملف"),
      optn("type", "النوع (image/document/video)"),
      optn("caption", "تعليق"),
      optn("phoneNumberId", "معرّف رقم الإرسال"),
    ],
  },

  /* ————— نوشن ————— */
  {
    id: "team-notion-append",
    employeeId: "*",
    provider: "notion",
    label: "إضافة محتوى إلى صفحة نوشن",
    inputs: [req("blockId", "معرّف الصفحة/الكتلة"), req("content", "المحتوى (سطر لكل فقرة)")],
  },
  {
    id: "team-notion-query",
    employeeId: "*",
    provider: "notion",
    label: "قراءة قاعدة بيانات نوشن",
    inputs: [req("databaseId", "معرّف القاعدة"), optn("pageSize", "عدد الصفوف")],
  },
  {
    id: "team-notion-db-item",
    employeeId: "*",
    provider: "notion",
    label: "إضافة صف إلى قاعدة نوشن",
    inputs: [
      req("databaseId", "معرّف القاعدة"),
      req("title", "العنوان"),
      optn("titleProperty", "اسم عمود العنوان"),
      optn("content", "المحتوى"),
    ],
  },

  /* ————— سِراج: لينكدإن ————— */
  {
    id: "sonny-linkedin-post",
    employeeId: "sonny",
    provider: "linkedin",
    label: "نشر منشور على لينكدإن",
    inputs: [req("text", "نص المنشور"), optn("organizationId", "معرّف صفحة الشركة (اختياري)")],
  },
  {
    id: "sonny-linkedin-article",
    employeeId: "sonny",
    provider: "linkedin",
    label: "نشر رابط/مقال على لينكدإن",
    inputs: [
      req("text", "نص المنشور"),
      req("url", "رابط المقال"),
      req("title", "عنوان المقال"),
      optn("description", "وصف قصير"),
      optn("organizationId", "معرّف صفحة الشركة"),
    ],
  },
  {
    id: "sonny-linkedin-stats",
    employeeId: "sonny",
    provider: "linkedin",
    label: "إحصاءات صفحة لينكدإن",
    inputs: [req("organizationId", "معرّف صفحة الشركة")],
  },

  /* ————— سِراج: إكس ————— */
  {
    id: "sonny-x-post",
    employeeId: "sonny",
    provider: "x",
    label: "نشر تغريدة",
    inputs: [req("text", "نص التغريدة")],
  },
  {
    id: "sonny-x-reply",
    employeeId: "sonny",
    provider: "x",
    label: "الرد على تغريدة",
    inputs: [req("tweetId", "معرّف التغريدة"), req("text", "نص الرد")],
  },
  {
    id: "sonny-x-dm",
    employeeId: "sonny",
    provider: "x",
    label: "رسالة خاصة على إكس",
    inputs: [req("userId", "معرّف المستخدم"), req("text", "النص")],
  },
  {
    id: "sonny-x-search",
    employeeId: "sonny",
    provider: "x",
    label: "بحث في تغريدات حديثة",
    inputs: [req("query", "الاستعلام"), optn("max", "عدد النتائج")],
  },

  /* ————— سِراج: إنستجرام ————— */
  {
    id: "sonny-ig-photo",
    employeeId: "sonny",
    provider: "instagram",
    label: "نشر صورة على إنستجرام",
    inputs: [req("imageUrl", "رابط الصورة"), optn("caption", "التعليق")],
  },
  {
    id: "sonny-ig-reel",
    employeeId: "sonny",
    provider: "instagram",
    label: "نشر ريلز",
    inputs: [req("videoUrl", "رابط الفيديو"), optn("caption", "التعليق"), optn("coverUrl", "غلاف")],
  },
  {
    id: "sonny-ig-story",
    employeeId: "sonny",
    provider: "instagram",
    label: "نشر ستوري",
    inputs: [optn("imageUrl", "رابط الصورة"), optn("videoUrl", "رابط الفيديو")],
  },
  {
    id: "sonny-ig-carousel",
    employeeId: "sonny",
    provider: "instagram",
    label: "نشر كاروسيل (عدة صور)",
    inputs: [req("imageUrls", "روابط الصور مفصولة بفاصلة"), optn("caption", "التعليق")],
  },
  {
    id: "sonny-ig-insights",
    employeeId: "sonny",
    provider: "instagram",
    label: "إحصاءات إنستجرام",
    inputs: [optn("mediaId", "معرّف منشور (اختياري)")],
  },
  {
    id: "sonny-ig-dm",
    employeeId: "sonny",
    provider: "instagram",
    label: "رد على رسالة إنستجرام",
    inputs: [req("recipientId", "معرّف المستخدم"), req("text", "النص")],
  },

  /* ————— سِراج: فيسبوك ————— */
  {
    id: "sonny-fb-post",
    employeeId: "sonny",
    provider: "facebook",
    label: "نشر منشور على صفحة فيسبوك",
    inputs: [req("message", "النص"), optn("link", "رابط")],
  },
  {
    id: "sonny-fb-photo",
    employeeId: "sonny",
    provider: "facebook",
    label: "نشر صورة على صفحة فيسبوك",
    inputs: [req("imageUrl", "رابط الصورة"), optn("caption", "التعليق")],
  },
  {
    id: "sonny-fb-insights",
    employeeId: "sonny",
    provider: "facebook",
    label: "إحصاءات صفحة فيسبوك",
    inputs: [optn("period", "المدة (day/week/days_28)")],
  },

  /* ————— سِراج: يوتيوب، تيك توك، بينترست، ريديت، بلوسكاي ————— */
  {
    id: "sonny-youtube-update",
    employeeId: "sonny",
    provider: "youtube",
    label: "تحديث بيانات فيديو يوتيوب",
    inputs: [
      req("videoId", "معرّف الفيديو"),
      req("title", "العنوان"),
      optn("description", "الوصف"),
      optn("tags", "كلمات مفتاحية"),
      optn("categoryId", "التصنيف"),
    ],
  },
  {
    id: "sonny-youtube-comment",
    employeeId: "sonny",
    provider: "youtube",
    label: "الرد على تعليق يوتيوب",
    inputs: [req("parentId", "معرّف التعليق"), req("text", "نص الرد")],
  },
  {
    id: "sonny-youtube-analytics",
    employeeId: "sonny",
    provider: "youtube",
    label: "تقرير أداء القناة",
    inputs: [optn("days", "عدد الأيام")],
  },
  {
    id: "sonny-tiktok-publish",
    employeeId: "sonny",
    provider: "tiktok",
    label: "نشر فيديو تيك توك",
    inputs: [
      req("title", "الوصف"),
      req("videoUrl", "رابط الفيديو"),
      optn("privacy", "الخصوصية (PUBLIC_TO_EVERYONE/SELF_ONLY)"),
    ],
  },
  {
    id: "sonny-tiktok-status",
    employeeId: "sonny",
    provider: "tiktok",
    label: "حالة نشر فيديو تيك توك",
    inputs: [req("publishId", "معرّف النشر")],
  },
  {
    id: "sonny-pinterest-board",
    employeeId: "sonny",
    provider: "pinterest",
    label: "إنشاء لوحة بينترست",
    inputs: [req("name", "اسم اللوحة"), optn("description", "الوصف")],
  },
  {
    id: "sonny-pinterest-analytics",
    employeeId: "sonny",
    provider: "pinterest",
    label: "إحصاءات بينترست",
    inputs: [optn("days", "عدد الأيام")],
  },
  {
    id: "sonny-reddit-comment",
    employeeId: "sonny",
    provider: "reddit",
    label: "الرد على منشور/تعليق ريديت",
    inputs: [req("thingId", "معرّف العنصر (t3_/t1_)"), req("text", "نص الرد")],
  },
  {
    id: "sonny-bluesky-reply",
    employeeId: "sonny",
    provider: "bluesky",
    label: "الرد على منشور بلوسكاي",
    inputs: [
      req("rootUri", "رابط المنشور الأصلي"),
      req("rootCid", "بصمة المنشور"),
      req("text", "نص الرد"),
      optn("parentUri", "رابط التعليق الأب"),
      optn("parentCid", "بصمة التعليق الأب"),
    ],
  },
  {
    id: "sonny-gbp-answer",
    employeeId: "sonny",
    provider: "google-business",
    label: "الإجابة على سؤال في نشاطي على جوجل",
    inputs: [req("question", "مسار السؤال"), req("text", "نص الإجابة")],
  },

  /* ————— سالم: CRM ————— */
  {
    id: "sam-hubspot-note",
    employeeId: "sam",
    provider: "hubspot",
    label: "تسجيل ملاحظة في هابسبوت",
    inputs: [req("body", "نص الملاحظة"), optn("contactId", "معرّف جهة الاتصال")],
  },
  {
    id: "sam-hubspot-task",
    employeeId: "sam",
    provider: "hubspot",
    label: "إنشاء مهمة متابعة في هابسبوت",
    inputs: [
      req("subject", "عنوان المهمة"),
      optn("body", "التفاصيل"),
      optn("dueAt", "تاريخ الاستحقاق"),
      optn("priority", "الأولوية"),
      optn("status", "الحالة"),
    ],
  },
  {
    id: "sam-hubspot-search",
    employeeId: "sam",
    provider: "hubspot",
    label: "بحث في جهات اتصال هابسبوت",
    inputs: [req("query", "كلمة البحث"), optn("limit", "عدد النتائج")],
  },
  {
    id: "sam-sf-opportunity",
    employeeId: "sam",
    provider: "salesforce",
    label: "إنشاء فرصة بيع في سيلزفورس",
    inputs: [
      req("Name", "اسم الفرصة"),
      req("CloseDate", "تاريخ الإغلاق (YYYY-MM-DD)"),
      optn("Amount", "القيمة"),
      optn("StageName", "المرحلة"),
      optn("AccountId", "معرّف الحساب"),
    ],
  },
  {
    id: "sam-sf-task",
    employeeId: "sam",
    provider: "salesforce",
    label: "مهمة متابعة في سيلزفورس",
    inputs: [
      req("Subject", "الموضوع"),
      optn("ActivityDate", "التاريخ"),
      optn("WhoId", "جهة الاتصال"),
      optn("Description", "التفاصيل"),
      optn("Status", "الحالة"),
    ],
  },
  {
    id: "sam-sf-query",
    employeeId: "sam",
    provider: "salesforce",
    label: "استعلام SOQL من سيلزفورس",
    inputs: [req("soql", "الاستعلام")],
  },
  {
    id: "sam-mailchimp-campaign",
    employeeId: "sam",
    provider: "mailchimp",
    label: "تجهيز حملة بريدية في ميلتشمب",
    inputs: [
      req("listId", "معرّف القائمة"),
      req("subject", "عنوان الرسالة"),
      req("fromName", "اسم المُرسل"),
      req("replyTo", "بريد الرد"),
      req("html", "محتوى الرسالة"),
      optn("title", "اسم الحملة"),
    ],
  },
  {
    id: "sam-mailchimp-send",
    employeeId: "sam",
    provider: "mailchimp",
    label: "إرسال حملة ميلتشمب",
    inputs: [req("campaignId", "معرّف الحملة")],
  },
  {
    id: "sam-mailchimp-tag",
    employeeId: "sam",
    provider: "mailchimp",
    label: "وسم مشترك في ميلتشمب",
    inputs: [req("listId", "معرّف القائمة"), req("email", "البريد"), req("tags", "الوسوم")],
  },
  {
    id: "sam-pipedrive-activity",
    employeeId: "sam",
    provider: "pipedrive",
    label: "نشاط متابعة في بايبدرايف",
    inputs: [
      req("subject", "الموضوع"),
      optn("type", "النوع (call/meeting/task)"),
      optn("dueDate", "التاريخ"),
      optn("dealId", "معرّف الصفقة"),
      optn("personId", "معرّف الشخص"),
    ],
  },
  {
    id: "sam-pipedrive-note",
    employeeId: "sam",
    provider: "pipedrive",
    label: "ملاحظة في بايبدرايف",
    inputs: [req("content", "النص"), optn("dealId", "معرّف الصفقة"), optn("personId", "معرّف الشخص")],
  },
  {
    id: "sam-intercom-contact",
    employeeId: "sam",
    provider: "intercom",
    label: "إنشاء جهة اتصال في إنتركوم",
    inputs: [req("email", "البريد"), optn("name", "الاسم"), optn("phone", "الجوال"), optn("role", "النوع")],
  },
  {
    id: "sam-intercom-reply",
    employeeId: "sam",
    provider: "intercom",
    label: "الرد على محادثة إنتركوم",
    inputs: [
      req("conversationId", "معرّف المحادثة"),
      req("adminId", "معرّف الموظف"),
      req("body", "نص الرد"),
      optn("messageType", "النوع (comment/note)"),
    ],
  },
  {
    id: "sam-intercom-close",
    employeeId: "sam",
    provider: "intercom",
    label: "إغلاق محادثة إنتركوم",
    inputs: [req("conversationId", "معرّف المحادثة"), req("adminId", "معرّف الموظف")],
  },
  {
    id: "sam-twilio-call",
    employeeId: "sam",
    provider: "twilio",
    label: "مكالمة صوتية برسالة مسجّلة",
    inputs: [
      req("from", "الرقم المُرسل"),
      req("to", "رقم المستلم"),
      req("say", "النص المنطوق"),
      optn("accountSid", "معرّف الحساب"),
    ],
  },
  {
    id: "sam-twilio-whatsapp",
    employeeId: "sam",
    provider: "twilio",
    label: "واتساب عبر تويليو",
    inputs: [
      req("from", "رقم الإرسال"),
      req("to", "رقم المستلم"),
      req("body", "النص"),
      optn("accountSid", "معرّف الحساب"),
    ],
  },
  {
    id: "sam-stripe-subscription",
    employeeId: "sam",
    provider: "stripe",
    label: "إنشاء اشتراك متكرر",
    inputs: [req("customer", "معرّف العميل"), req("priceId", "معرّف السعر"), optn("trialDays", "أيام تجريبية")],
  },
  {
    id: "sam-stripe-refund",
    employeeId: "sam",
    provider: "stripe",
    label: "استرداد مبلغ",
    inputs: [req("paymentIntent", "معرّف الدفعة"), optn("amount", "المبلغ بالهللة")],
  },
  {
    id: "sam-stripe-charges",
    employeeId: "sam",
    provider: "stripe",
    label: "آخر المدفوعات",
    inputs: [optn("customer", "معرّف العميل"), optn("limit", "العدد")],
  },
  {
    id: "sam-airtable-create",
    employeeId: "sam",
    provider: "airtable",
    label: "إضافة صف في إيرتيبل",
    inputs: [
      req("baseId", "معرّف القاعدة"),
      req("table", "اسم الجدول"),
      req("fields", 'الحقول بصيغة JSON مثل {"Name":"أحمد"}'),
    ],
  },
  {
    id: "sam-airtable-update",
    employeeId: "sam",
    provider: "airtable",
    label: "تحديث صف في إيرتيبل",
    inputs: [
      req("baseId", "معرّف القاعدة"),
      req("table", "اسم الجدول"),
      req("recordId", "معرّف الصف"),
      req("fields", "الحقول بصيغة JSON"),
    ],
  },
  {
    id: "sam-airtable-list",
    employeeId: "sam",
    provider: "airtable",
    label: "قراءة صفوف إيرتيبل",
    inputs: [
      req("baseId", "معرّف القاعدة"),
      req("table", "اسم الجدول"),
      optn("formula", "شرط تصفية"),
      optn("max", "عدد الصفوف"),
    ],
  },

  /* ————— شيتس ودرايف وتصميم ————— */
  {
    id: "sam-update-sheet-row",
    employeeId: "sam",
    provider: "sheets",
    label: "تحديث صف في جوجل شيتس",
    inputs: [
      req("sheetId", "معرّف الملف"),
      req("worksheetId", "معرّف الورقة"),
      req("rowNumber", "رقم الصف"),
      req("row", "القيم مفصولة بفاصلة"),
    ],
  },
  {
    id: "adam-read-sheet",
    employeeId: "adam",
    provider: "sheets",
    label: "قراءة بيانات من شيتس",
    inputs: [req("sheetId", "معرّف الملف"), req("worksheetId", "معرّف الورقة")],
  },
  {
    id: "dana-drive-share",
    employeeId: "dana",
    provider: "drive",
    label: "مشاركة ملف من درايف",
    inputs: [req("fileId", "معرّف الملف"), optn("email", "بريد الشخص"), optn("role", "الصلاحية")],
  },
  {
    id: "dana-figma-export",
    employeeId: "dana",
    provider: "figma",
    label: "تصدير تصميم من فيجما",
    inputs: [
      req("fileId", "معرّف الملف"),
      req("nodeIds", "معرّفات العناصر"),
      optn("format", "الصيغة"),
      optn("scale", "الدقة"),
    ],
  },
  {
    id: "dana-canva-export",
    employeeId: "dana",
    provider: "canva",
    label: "تصدير تصميم كانفا",
    inputs: [req("designId", "معرّف التصميم"), optn("format", "الصيغة")],
  },

  /* ————— تواصل الفريق ————— */
  {
    id: "team-slack-update",
    employeeId: "*",
    provider: "slack",
    label: "تعديل رسالة سلاك",
    inputs: [req("channel", "القناة"), req("ts", "طابع الرسالة"), req("text", "النص الجديد")],
  },
  {
    id: "team-slack-react",
    employeeId: "*",
    provider: "slack",
    label: "إضافة تفاعل على رسالة سلاك",
    inputs: [req("channel", "القناة"), req("ts", "طابع الرسالة"), req("emoji", "اسم الإيموجي")],
  },
  {
    id: "team-slack-dm",
    employeeId: "*",
    provider: "slack",
    label: "رسالة خاصة في سلاك",
    inputs: [req("userId", "معرّف المستخدم"), req("text", "النص")],
  },
  {
    id: "team-discord-embed",
    employeeId: "*",
    provider: "discord",
    label: "بطاقة منسّقة في ديسكورد",
    inputs: [req("channel", "القناة"), req("title", "العنوان"), req("description", "الوصف"), optn("url", "رابط")],
  },
  {
    id: "team-telegram-photo",
    employeeId: "*",
    provider: "telegram",
    label: "إرسال صورة على تيليجرام",
    inputs: [req("chatId", "معرّف المحادثة"), req("photoUrl", "رابط الصورة"), optn("caption", "تعليق")],
  },
  {
    id: "team-trello-move",
    employeeId: "*",
    provider: "trello",
    label: "نقل بطاقة تريلو",
    inputs: [req("cardId", "معرّف البطاقة"), req("idList", "معرّف القائمة الجديدة")],
  },
  {
    id: "team-trello-comment",
    employeeId: "*",
    provider: "trello",
    label: "تعليق على بطاقة تريلو",
    inputs: [req("cardId", "معرّف البطاقة"), req("text", "النص")],
  },
  {
    id: "team-asana-comment",
    employeeId: "*",
    provider: "asana",
    label: "تعليق على مهمة أسانا",
    inputs: [req("taskId", "معرّف المهمة"), req("text", "النص")],
  },
  {
    id: "team-asana-complete",
    employeeId: "*",
    provider: "asana",
    label: "إغلاق مهمة أسانا",
    inputs: [req("taskId", "معرّف المهمة"), optn("completed", "منجزة (true/false)")],
  },
  {
    id: "team-jira-transition",
    employeeId: "*",
    provider: "jira",
    label: "تحويل حالة مهمة جيرا",
    inputs: [req("cloudId", "معرّف المساحة"), req("issueKey", "رقم المهمة"), req("transitionId", "معرّف الحالة")],
  },
  {
    id: "team-jira-comment",
    employeeId: "*",
    provider: "jira",
    label: "تعليق على مهمة جيرا",
    inputs: [req("cloudId", "معرّف المساحة"), req("issueKey", "رقم المهمة"), req("text", "النص")],
  },
  {
    id: "team-clickup-status",
    employeeId: "*",
    provider: "clickup",
    label: "تحديث مهمة كليك أب",
    inputs: [req("taskId", "معرّف المهمة"), optn("status", "الحالة"), optn("name", "الاسم")],
  },
  {
    id: "team-clickup-comment",
    employeeId: "*",
    provider: "clickup",
    label: "تعليق على مهمة كليك أب",
    inputs: [req("taskId", "معرّف المهمة"), req("text", "النص")],
  },
  {
    id: "team-monday-column",
    employeeId: "*",
    provider: "monday",
    label: "تحديث أعمدة عنصر في مونداي",
    inputs: [
      req("boardId", "معرّف اللوح"),
      req("itemId", "معرّف العنصر"),
      req("columnValues", "القيم بصيغة JSON"),
    ],
  },
  {
    id: "team-monday-update",
    employeeId: "*",
    provider: "monday",
    label: "تحديث/تعليق على عنصر مونداي",
    inputs: [req("itemId", "معرّف العنصر"), req("body", "النص")],
  },

  /* ————— آدم: الإعلانات والقياس ————— */
  {
    id: "adam-ga4-realtime",
    employeeId: "adam",
    provider: "analytics",
    label: "الزوار الآن (لحظي)",
    inputs: [req("property", "معرّف الموقع في GA4")],
  },
  {
    id: "adam-ga4-top-pages",
    employeeId: "adam",
    provider: "analytics",
    label: "أفضل الصفحات أداءً",
    inputs: [req("property", "معرّف الموقع في GA4"), optn("days", "عدد الأيام")],
  },
  {
    id: "adam-meta-insights",
    employeeId: "adam",
    provider: "meta-ads",
    label: "تقرير حملات ميتا",
    inputs: [req("adAccountId", "معرّف الحساب الإعلاني"), optn("datePreset", "المدة")],
  },
  {
    id: "adam-meta-campaign",
    employeeId: "adam",
    provider: "meta-ads",
    label: "إنشاء حملة ميتا (متوقفة للمراجعة)",
    inputs: [
      req("adAccountId", "معرّف الحساب الإعلاني"),
      req("name", "اسم الحملة"),
      optn("objective", "الهدف"),
      optn("dailyBudget", "الميزانية اليومية بالهللة"),
    ],
  },
  {
    id: "adam-meta-toggle",
    employeeId: "adam",
    provider: "meta-ads",
    label: "إيقاف/تشغيل حملة أو إعلان",
    inputs: [req("objectId", "معرّف العنصر"), optn("status", "الحالة (PAUSED/ACTIVE)")],
  },
  {
    id: "adam-gads-report",
    employeeId: "adam",
    provider: "google-ads",
    label: "تقرير حملات جوجل الإعلانية",
    inputs: [
      req("customerId", "معرّف الحساب"),
      optn("query", "استعلام مخصص"),
      optn("loginCustomerId", "حساب الإدارة"),
    ],
  },
  {
    id: "adam-gads-toggle",
    employeeId: "adam",
    provider: "google-ads",
    label: "إيقاف/تشغيل حملة جوجل",
    inputs: [
      req("customerId", "معرّف الحساب"),
      req("campaignId", "معرّف الحملة"),
      optn("status", "الحالة"),
      optn("loginCustomerId", "حساب الإدارة"),
    ],
  },

  /* ————— نور: سيو ————— */
  {
    id: "nour-gsc-pages",
    employeeId: "nour",
    provider: "search-console",
    label: "أفضل الصفحات في نتائج جوجل",
    inputs: [req("siteUrl", "رابط الموقع"), optn("days", "عدد الأيام")],
  },
  {
    id: "nour-gsc-sitemap",
    employeeId: "nour",
    provider: "search-console",
    label: "إرسال خريطة الموقع",
    inputs: [req("siteUrl", "رابط الموقع"), req("sitemapUrl", "رابط الخريطة")],
  },
  {
    id: "nour-gsc-inspect",
    employeeId: "nour",
    provider: "search-console",
    label: "فحص فهرسة صفحة",
    inputs: [req("siteUrl", "رابط الموقع"), req("pageUrl", "رابط الصفحة")],
  },
];
