
ALTER TABLE public.tasks
  ADD COLUMN IF NOT EXISTS kind TEXT NOT NULL DEFAULT 'مهمة',
  ADD COLUMN IF NOT EXISTS steps JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS scheduled TEXT;
